version: '3'

services:
  postgres:
    image: 'postgres:9.5'
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - "5432:5432"

  app:
    depends_on:
      - 'postgres'
    build: .
    command: bash start
    ports:
      - '3000:3000'
    volumes:
      - '.:/DevOneBitCode'


  box:
    image: busybox
    volumes:
      - /box


volumes:
  postgres:
  box: